# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableauNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=42)),
                ('note', models.SmallIntegerField()),
            ],
        ),
    ]
