# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='output',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('note', models.SmallIntegerField()),
                ('user', models.CharField(max_length=100)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableau.input')),
            ],
        ),
    ]
