# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0003_remove_output_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='input',
        ),
        migrations.AddField(
            model_name='output',
            name='nbRect',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='output',
            name='nbRectWhite',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='output',
            name='note',
            field=models.SmallIntegerField(default=1),
        ),
    ]
