# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0005_auto_20171216_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='nbRect',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='output',
            name='nbRectWhite',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='output',
            name='note',
            field=models.SmallIntegerField(),
        ),
    ]
