# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0007_auto_20171216_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.SmallIntegerField(default=1)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tableau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbRect', models.SmallIntegerField(default=1)),
                ('nbRectWhite', models.SmallIntegerField(default=1)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableau.note')),
            ],
        ),
        migrations.DeleteModel(
            name='output',
        ),
    ]
