# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0009_auto_20171216_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableau',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
