# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0010_auto_20171216_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tableau',
            new_name='tableaux',
        ),
    ]
