# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0013_auto_20171216_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableaux',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
