# Generated by Django 2.0 on 2017-12-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0014_tableaux_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaux',
            name='data',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='tableaux',
            name='note',
            field=models.ForeignKey(on_delete='cascade', to='tableau.note'),
        ),
    ]
