# Generated by Django 2.0 on 2017-12-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0017_auto_20171217_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='donnee',
            field=models.TextField(default=''),
        ),
    ]
