# Generated by Django 2.0 on 2017-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0018_auto_20171217_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableaux',
            name='progressive',
            field=models.BooleanField(default=False),
        ),
    ]
